package com.ringtonehaptics.app.domain.model

import kotlinx.serialization.Serializable

@Serializable
data class HapticClip(
    val id: Long = System.nanoTime(),
    val patternType: HapticPatternType = HapticPatternType.THUMP,
    val startMs: Long,
    val durationMs: Int = patternType.defaultDurationMs,
    val intensity: Float = 0.85f, // 0.05f to 1.0f
    val activeBraking: Boolean = true,
    val carrierFreqHz: Float = 160.0f, // Nominal Pixel LRA resonance
    val carrierFreqEndHz: Float? = null, // non-null = ramp carrierFreqHz -> this across the clip (BUILDUP/SWELL)
    val isAutoGenerated: Boolean = true,
    val instrument: HapticInstrument = HapticInstrument.KICK
) {
    val endMs: Long get() = startMs + durationMs
}
